name: "游눠 Solicitud de Funcionalidad"
description: Crear un nuevo ticket para una solicitud de nueva funcionalidad. Por favor, a침ade una label de "priority/XXXX" de las disponibles en funci칩n de la prioridad de la funcionalidad.
title: "[FEATURE_REQUEST] - <t칤tulo>"
labels: [
  "enhancement"
]
body:
  - type: textarea
    id: descripcion
    attributes:
      label: "Descripci칩n"
      description: Proporcione una descripci칩n detallada de la funcionalidad
      placeholder: Describe en detalle tu solicitud de funcionalidad
    validations:
      required: true
  - type: textarea
    id: issue_referencia
    attributes:
      label: "Issue de Referencia"
      description: Issue comunes
      placeholder: "#IDs de issue"
    validations:
      required: false
